### ISSUE TITLE
IOIO for PC: PwmOutput does not work

### ISSUE THREAD

**Issue by Joe7M** [smallbasic/smallbasic.plugins#8]
Here my basic program:

```
import ioio

led = ioio.openPwmOutput(46)

print "wait for connect"
ioio.waitForConnect(10)
print "ready!!!"


for DutyCycle = 0 to 1 step 0.1
    led.setDutyCycle(DutyCycle)
    delay 100
next

print "Done"
```

Alternative  `ioio.openPwmOutput(0)`, because the onboard LED supports PWM, too.

Error message:

```
[I/IOIOImpl] created
[I/IOIOBaseApplicationHelper] Using IOIOLib version: IOIO0507
[D/IOIOConnectionRegistry] Successfully added bootstrap class: ioio.smallbasic.pc.SerialPortIOIOConnectionBootstrap
[I/PwmOutput] created
wait for connect
[D/SerialPortIOIOConnectionBootstrap] Adding serial port IOIO0
[D/IOIOImpl] Waiting for IOIO connection
[V/IOIOImpl] Waiting for underlying connection
[V/IOIOImpl] Waiting for handshake
[I/IncomingState] IOIO Connection established. Hardware ID: SPRK0020 Bootloader ID: IOIO0402 Firmware ID: IOIO0506
[V/IOIOImpl] Querying for required interface ID
[V/IOIOImpl] Required interface ID is supported
[I/IOIOImpl] IOIO connection established
Exception in thread "main" ioio.smallbasic.IOIOException: / by zero
        at ioio.smallbasic.IOTask.handleError(IOTask.java:24)
        at ioio.smallbasic.IOIOImpl.waitForConnect(IOIOImpl.java:72)


 * RTE-ERROR AT ledpwm.bas:6 * 
Description:
LIB:IOIO: Error: [/ by zero]

[D/IOIOImpl] Client requested disconnect.
[I/IOIOProtocol] IOIO disconnected
[D/IOIOImpl] Client requested disconnect.
[D/IOIOImpl] Client requested disconnect.
[I/IOService] disconnected
[D/IOIOBaseApplicationHelper] IOIOThread is exiting
```

Would it be possible to set the frequency, when calling `ioio.openPwmOutput` ?

**Comment by chrisws** [comment]
That should be fixed now. 

I have lots of usb cables, but only 1 that works with the board lol.

**Comment by Joe7M** [comment]
Thank you. Works now.
